### ISSUE TITLE
Need a Markdown version

### ISSUE THREAD

**Issue by cshubhamrao** [NextTechLabAP/IoT-Roadmap#1]
Hey, it'd be great if we have a Markdown version of this roadmap similar to [McCarthy Lab's Roadmap](https://github.com/NextTechLabAP/McCarthy-Lab-Roadmap) and other labs'. Benefits include being able to search and update easily

**Comment by cshubhamrao** [comment]
@S-FK @AgniswarPaul  ping, please delegate to other associates/members if you guys are busy

**Comment by S-FK** [comment]
@cshubhamrao I don't have assign access.

**Comment by S-FK** [comment]
PR Requested @cshubhamrao @Dexter2389

**Comment by Dexter2389** [comment]
Thanks for your valuable contribution @S-FK

**Comment by S-FK** [comment]
Thanks for merging! @Dexter2389

**Comment by S-FK** [comment]
Thanks for accepting the PR @Dexter2389
